### ISSUE TITLE
Arduino ESP8266 core function calls issue

### ISSUE THREAD

**Issue by p-m-x** [heleon19/webconfig#2]
lib\WebConfig\src\webconfig.cpp:61:101: error: no matching function for call to 'ESP8266WebServer::on(const __FlashStringHelper*, WebConfig::init(WebConfigParam*, int)::__lambda1)'
_server.on(F("/custom.js"), [](){ _server.send(200, F("application/javascript"), _customScript); });

lib\WebConfig\src\webconfig.cpp: In member function 'void WebConfig::updateWifi()':
lib\WebConfig\src\webconfig.cpp:305:95: error: no matching function for call to 'ESP8266WiFiClass::softAP(const char*, const char*, int, bool, int)'
WiFi.softAP(getParameter(PARAM_NAME_AP_SSID), getParameter(PARAM_NAME_AP_PSWD), 11, false, 1);

**Comment by heleon19** [comment]
Thanks for reporting that.

I used the ESP8266 stage version, due to the main release was slow and not stable. The SDK has changed, if you want to use the library for the main release you have to change code. But I recommend to change the espressif8266_stage version:
platform.ini:
[env:nodemcuv2]
platform = espressif8266_stage
board = nodemcuv2
framework = arduino

For the main release remove the F() makros for this strings:
  _server.on("/", [](){ _server.send(200, F("text/html"), _mainWebPage); });
  _server.on("/custom.js", [](){ _server.send(200, F("application/javascript"), _customScript); });
  _server.on("/custom.css", [](){ _server.send(200, F("text/css"), _customCss); });
  _server.on("/default.css", [](){ _server.send(200, F("text/css"), _defaultCss); });
  _server.on("/config.json", [=](){ sendConfigJson(); });
  _server.on("/store", [=](){ receiveConfig(); });

And SSID hidden was an integer:
WiFi.softAP(getParameter(PARAM_NAME_AP_SSID), getParameter(PARAM_NAME_AP_PSWD), 11, 0, 1);

**Comment by p-m-x** [comment]
Thanks for info, I have fix for that

2017-11-20 23:09 GMT+01:00 heleon19 <notifications@github.com>:
